### ISSUE TITLE
Crash When Leaving Conference Call

### ISSUE THREAD

**Issue by CSX8600** [RavenholmZombie/Immersibrook#47]
Server crash when leaving conference call when at least one player involved has disconnected (possible theory)

https://pastebin.com/vMcu4rfh

**Comment by RavenholmZombie** [comment]
```
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/8/22 11:02 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.mesabrook.ib.telecom.CallManager.tick(CallManager.java:112)
	at com.mesabrook.ib.telecom.handlers.ServerTickEventHandler.onTick(ServerTickEventHandler.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_122_ServerTickEventHandler_onTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```
I think your theory may be correct.

**Comment by CSX8600** [comment]
Actually it looks like it might be because I never considered how to handle logging conference calls in the call history log

https://github.com/RavenholmZombie/Immersibrook/blob/ea788e8cd42a01f6db9bd178228f18d7665838f0/src/main/java/com/mesabrook/ib/telecom/CallManager.java#L112

**Comment by CSX8600** [comment]
This needs to be reopened - this issue is still present.

**Comment by RavenholmZombie** [comment]
Repoened

**Comment by CSX8600** [comment]
Can't replicate. Carefully documented steps will be required before this can be closed.
